Main:
  path: /
  controller: App\Controller\MainController::index

Main_create:
  path: /create
  controller: App\Controller\MainController::create

Main_display:
  path: /display/{id}
  controller: App\Controller\MainController::display

Main_modify:
  path: /modify/{id}
  controller: App\Controller\MainController::modify

City:
  path: /city
  controller: App\Controller\CityController::index

Campus:
  path: /campus
  controller: App\Controller\CampusController::index

Profil_user:
  path: /profil/{id<\d+>}
  controller: App\Controller\UserController::seeUser

Check_password:
  path: /profil/check
  controller: App\Controller\UserController::checkPassword

Update_user:
  path: /profil/update
  controller: App\Controller\UserController::updateUser

User:
  path: /profil
  controller: App\Controller\UserController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

Admin:
    path: /admin
    controller: App\Controller\AdminController::index

Admin_register:
    path: /admin/register
    controller: App\Controller\RegistrationController::register

Admin_register_file:
  path: /admin/registerFile
  controller: App\Controller\RegistrationController::registerViaFile

Admin_deactivateUser:
    path: /admin/deactivate
    controller: App\Controller\AdminController::deactivateUser

Admin_deleteUser:
    path: /admin/delete
    controller: App\Controller\AdminController::deleteUser

Admin_cancelTrip:
    path: /admin/cancel
    controller: App\Controller\AdminController::cancelTrip


