Main:
    path: /
    controller: App\Controller\MainController::index

City:
    path: /city
    controller: App\Controller\CityController::index

Campus:
    path: /campus
    controller: App\Controller\CampusController::index

User:
    path: /profil
    controller: App\Controller\UserController::index

Trip:
    path: /trip
    controller: App\Controller\TripController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

Admin:
    path: /admin
    controller: App\Controller\AdminController::index

Admin_register:
    path: /admin/register
    controller: App\Controller\RegistrationController::register

Admin_deactivateUser:
    path: /admin/deactivate
    controller: App\Controller\AdminController::deactivateUser

Admin_deleteUser:
    path: /admin/delete
    controller: App\Controller\AdminController::deleteUser

Admin_cancelTrip:
    path: /admin/cancel
    controller: App\Controller\AdminController::cancelTrip