Main:
    path: /
    controller: App\Controller\MainController::index

City:
    path: /city
    controller: App\Controller\CityController::index

Campus:
    path: /campus
    controller: App\Controller\CampusController::index

User:
    path: /profil
    controller: App\Controller\UserController::index

Trip:
    path: /trip
    controller: App\Controller\TripController::index

Registration:
    path: /registration
    controller: App\Controller\RegistrationController::index