Main:
  path: /
  controller: App\Controller\MainController::index

Main_create:
  path: /create
  controller: App\Controller\MainController::create

Main_display:
  path: /display/{id}
  controller: App\Controller\MainController::display

Main_modify:
  path: /modify/{id}
  controller: App\Controller\MainController::modify

Main_message_create:
  path: /Cancel/{id}
  controller: App\Controller\MainController::CreateMessage

City:
  path: /city
  controller: App\Controller\CityController::index

Campus:
  path: /campus
  controller: App\Controller\CampusController::index

Profil_user:
  path: /profil/{id<\d+>}
  controller: App\Controller\UserController::seeUser

All_users:
  path: /admin/users
  controller: App\Controller\UserController::allUsers

Check_password:
  path: /profil/check
  controller: App\Controller\UserController::checkPassword

Update_user:
  path: /profil/update
  controller: App\Controller\UserController::updateUser

Delete_user:
  path: /admin/users/delete/{id<\d+>}
  controller: App\Controller\UserController::deleteUser

Activate_user:
  path: /admin/users/activate/{id<\d+>}
  controller: App\Controller\UserController::activateUser

Desactivate_user:
  path: /admin/users/desactivate/{id<\d+>}
  controller: App\Controller\UserController::desactivateUser

User:
  path: /profil
  controller: App\Controller\UserController::index

login:
  path: /login
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

Admin:
  path: /admin
  controller: App\Controller\AdminController::index

Admin_register:
  path: /admin/register
  controller: App\Controller\RegistrationController::register

Admin_register_file:
  path: /admin/registerFile
  controller: App\Controller\RegistrationController::registerViaFile

Admin_deactivateUser:
  path: /admin/deactivate
  controller: App\Controller\AdminController::deactivateUser

Admin_deleteUser:
  path: /admin/delete
  controller: App\Controller\AdminController::deleteUser

Admin_cancelTrip:
  path: /admin/cancel
  controller: App\Controller\AdminController::cancelTrip

Admin_villes:
  path: /admin/villes
  controller: App\Controller\VilleController::index

Admin_campus:
  path: /admin/campus
  controller: App\Controller\CampusController::index

Admin_modify_campus:
  path: /admin/campus/{id<\d+>}
  controller: App\Controller\CampusController::update

Admin_delete_campus:
  path: /admin/campus/delete/{id<\d+>}
  controller: App\Controller\CampusController::delete

Admin_ville_update:
  path: /admin/villes/{id<\d+>}
  controller: App\Controller\VilleController::update

Get_lieu:
  path: /lieu/{id<\d+>}
  controller: App\Controller\LieuController::getLieu

Add_lieu:
  path: /lieu/add
  controller: App\Controller\LieuController::index

Reset_password:
  path: /reset-password
  controller: App\Controller\ResetPasswordController::request

Password_checkEmail:
  path: /check-email
  controller: App\Controller\ResetPasswordController::checkEmail

Password_reset:
  path: /reset/{token}
  controller: App\Controller\ResetPasswordController::reset

Password_reset1:
  path: /reset
  controller: App\Controller\ResetPasswordController::reset
